FROM gitlab/gitlab-ce:8.10.5-ce.0
MAINTAINER Stephan Kotze

RUN \
	mkdir certificates && \
	openssl genrsa -out certificates/server.key 1024 && \
	openssl req -new -key certificates/server.key -out certificates/server.csr -days 999 -subj "/C=UK/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" && \
	openssl x509 -req -days 999 -in certificates/server.csr -signkey certificates/server.key -out certificates/server.crt

RUN \
	echo "registry_nginx['ssl_certificate'] = \"/certificates/server.crt\"" >> /etc/gitlab/gitlab.rb && \
	echo "registry_nginx['ssl_certificate_key'] = \"/certificates/server.key\"" >> /etc/gitlab/gitlab.rb 
#	echo "registry_external_url 'https://set_me_to_docker_hostname'" /etc/gitlab/gitlab.rb >> /etc/gitlab/gitlab.rb

# install entrypoint script
COPY entry.sh /bin/entry.sh
RUN chmod +x /bin/entry.sh

CMD ["/bin/entry.sh"]






