version: '2'
services:
  gitlab:  
   container_name: gitlab
   image: gitlab/gitlab-ce:8.10.5-ce.0
   hostname: ${GITLAB_CONTAINER_HOSTNAME}
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://127.0.0.1:8050'
       gitlab_rails['gitlab_shell_ssh_port'] = 522
   ports:
    - "8050:8050"
    - "522:22"
   volumes_from:
    - ci_stack_volume
   restart: always

  registry:  
   container_name: registry
   image: registry:2.5.0
   hostname: ${REGISTRY_CONTAINER_HOSTNAME}
   ports:
    - "5000:5000"
   volumes_from:
    - ci_stack_volume
   restart: always

  jenkins:  
   container_name: jenkins
   build: jenkins_with_docker_image
   hostname: ${JENKINS_CONTAINER_HOSTNAME}
   ports:
    - "8080:8080"
    - "50000:50000"
   volumes_from:
    - ci_stack_volume
   environment:
    - REGISTRY_CONTAINER_HOSTNAME=${REGISTRY_CONTAINER_HOSTNAME}
    - DOCKERHOST_HOSTNAME=${DOCKERHOST_HOSTNAME}
    - CI_STACK_VOLUME_NAME=${CI_STACK_VOLUME_NAME}
   restart: always

  ci_stack_volume:
    container_name: ${CI_STACK_VOLUME_NAME}
    image: jenkins:2.7.2
    entrypoint: "true"
    volumes:
    - ${VOLUMES_DIR}/gitlab/etc/gitlab:/etc/gitlab
    - ${VOLUMES_DIR}/gitlab/var/log/gitlab:/var/log/gitlab
    - ${VOLUMES_DIR}/gitlab/var/opt/gitlab:/var/opt/gitlab
    - ${VOLUMES_DIR}/registry/var/lib/registry:/var/lib/registry
    - ${VOLUMES_DIR}/registry/etc/docker/registry/:/etc/docker/registry/
    - ${VOLUMES_DIR}/jenkins/var/jenkins_home:/var/jenkins_home
    - ${VOLUMES_DIR}/my_ivy_cache:/ivy_cache
    - ${VOLUMES_DIR}/target:/target
    - /var/run/docker.sock:/var/run/docker.sock
