version: '2'
services:
  gitlab:  
   container_name: gitlab
   image: gitlab/gitlab-ce:8.10.5-ce.0
   hostname: ${GITLAB_CONTAINER_HOSTNAME}
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://127.0.0.1:8050'
       gitlab_rails['gitlab_shell_ssh_port'] = 522
   ports:
    - "8050:80"
    - "522:22"
    - "443:443"
   networks:
    ci_stack_net:
       aliases: 
         - ${JENKINS_CONTAINER_HOSTNAME}
   volumes_from:
    - ci_stack_volume
   environment:
    - REGISTRY_CONTAINER_HOSTNAME=${REGISTRY_CONTAINER_HOSTNAME}
    - DOCKERHOST_HOSTNAME=${DOCKERHOST_HOSTNAME}
    - CI_STACK_VOLUME_NAME=${CI_STACK_VOLUME_NAME}
    - GITLAB_CONTAINER_HOSTNAME=${CI_STACK_VOLUME_NAME}
    - REGISTRY_PORT=${REGISTRY_PORT}
   restart: always

  jenkins:  
   container_name: jenkins
   build: jenkins_with_docker_image
   hostname: ${JENKINS_CONTAINER_HOSTNAME}
   ports:
    - "8080:8080"
    - "50000:50000"
   networks:
    ci_stack_net:
       aliases: 
         - ${JENKINS_CONTAINER_HOSTNAME}
   volumes_from:
    - ci_stack_volume
   environment:
    - DOCKERHOST_HOSTNAME=${DOCKERHOST_HOSTNAME}
    - REGISTRY_PORT=${REGISTRY_PORT}
    - CI_STACK_VOLUME_NAME=${CI_STACK_VOLUME_NAME}
    - GITLAB_CONTAINER_HOSTNAME=${CI_STACK_VOLUME_NAME}
    - REGISTRY_CONTAINER_HOSTNAME=${REGISTRY_CONTAINER_HOSTNAME}
   restart: always

  registry:
   restart: always
   image: registry:2
   container_name: registry
   hostname: ${REGISTRY_CONTAINER_HOSTNAME}
   ports:
    - ${REGISTRY_PORT}:5000
   volumes_from:
    - ci_stack_volume

  ci_stack_volume:
    container_name: ${CI_STACK_VOLUME_NAME}
    image: jenkins:2.7.2
    entrypoint: "true"
    volumes:
    - ${VOLUMES_DIR}/gitlab/etc/gitlab:/etc/gitlab
    - ${VOLUMES_DIR}/gitlab/var/log/gitlab:/var/log/gitlab
    - ${VOLUMES_DIR}/gitlab/var/opt/gitlab:/var/opt/gitlab
    - ${VOLUMES_DIR}/jenkins/var/jenkins_home:/var/jenkins_home
    - ${VOLUMES_DIR}/my_ivy_cache:/ivy_cache
    - ${VOLUMES_DIR}/target:/target
    - ${VOLUMES_DIR}/registry/var/lib/registry:/var/lib/registry
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  ci_stack_net:
